# Gunakan Python image ringan
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy requirements
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy semua source code
COPY . .

# Expose port (Fly default 8080)
EXPOSE 8080

# Jalankan FastAPI
CMD ["uvicorn", "api.index:app", "--host", "0.0.0.0", "--port", "8080"]

RUN apt-get update && apt-get install -y \
    wget \
    curl \
    gnupg \
    && rm -rf /var/lib/apt/lists/*

RUN playwright install --with-deps
